version: "1.0.0"
services:
  worker:
    build: .
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
    ports:
      - "3000:3000"  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_ID: ${SESSION_ID}
      REMOVEBG_KEY: ${REMOVEBG_KEY}
      PREFIX: ${PREFIX}
      WORKTYPE: ${WORKTYPE}
      REACT: ${REACT}
  redis:
    image: redis
volumes:
  logvolume01: {}
